[package]
name = "type-exercise-starter-supplied-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
homepage.workspace = true
description = "Cumulative public tests for the Type Exercise in Rust starter"

[dependencies]
anyhow = "1"
bitvec = "1"
type-exercise-starter-expr = { version = "0.1.1", path = "../expr" }
type-exercise-starter-core = { version = "0.1.1", path = "../core" }
