[package]
name = "type-exercise-starter-expr"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
homepage.workspace = true
description = "Learner-owned expression engine for the Type Exercise in Rust course"

[dependencies]
anyhow = "1"
bitvec = "1"
type-exercise-starter-core = { version = "0.1.1", path = "../core" }
