[package]
name = "expr-template"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
expr-common = { path = "../expr-common" }

[build-dependencies]
anyhow.workspace = true
expr-template-impl = { path = "../expr-template-impl" }
