[package]
name = "type-exercise-expr"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1"
bitvec = "1"
type-exercise-core = { path = "../core", version = "0.2.0-alpha.1" }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "expression"
harness = false
