[package]
name = "expr-impl"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
expr-common = { path = "../expr-common" }
expr-template = { path = "../expr-template" }
expr-macro-rules = { path = "../expr-macro-rules" }
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "expression"
harness = false
