[package]
name = "type-exercise-checkpoint-12-supplied-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1"
bitvec = "1"
type-exercise-checkpoint-12-expr = { path = "../expr" }
type-exercise-checkpoint-12-core = { path = "../core" }
