[book]
authors = ["Alex Chi"]
description = "A Rust course that builds a typed, auto-vectorized database expression engine"
language = "en"
src = "src"
title = "Build a Typed Database Expression Engine in Rust"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/skyzh/type-exercise-in-rust"
