name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable Rust
        run: |
          rustup update stable
          rustc --version
      - uses: taiki-e/install-action@nextest
      - name: Check maintained final artifact format
        run: cargo fmt --package type-exercise-core --package type-exercise-expr -- --check
      - name: Clippy maintained final artifact
        run: cargo clippy --package type-exercise-core --package type-exercise-expr --all-targets --locked -- -D warnings
      - name: Test maintained final artifact
        run: cargo nextest run --package type-exercise-core --package type-exercise-expr --locked
      - name: Test maintained final artifact documentation
        run: cargo test --package type-exercise-core --package type-exercise-expr --doc --locked
