name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable Rust
        run: |
          rustup update stable
          rustc --version
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@mdbook
      - name: Check current workspace format
        run: cargo fmt --all -- --check
      - name: Clippy workspace
        run: cargo clippy --workspace --all-targets --locked -- -D warnings
      - name: Test workspace
        run: cargo nextest run --workspace --locked
      - name: Test workspace documentation
        run: cargo test --workspace --doc --locked
      - name: Test course
        run: mdbook test course
